<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="9.0.5" />
    <ProjectReference Include="..\Akeldov.Data\Akeldov.Data.csproj" />
    <InternalsVisibleTo Include="Akeldov.Data.PostgreSql.Tests" />
  </ItemGroup>

</Project>
