<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Akeldov.Data.Tests" />
    <InternalsVisibleTo Include="Akeldov.Data.SqlServer" />
    <InternalsVisibleTo Include="Akeldov.Data.PostgreSql" />
    <InternalsVisibleTo Include="Akeldov.Data.SqlServer.Tests" />
    <InternalsVisibleTo Include="Akeldov.Data.PostgreSql.Tests" />
  </ItemGroup>

</Project>
